version: '3.1'
services:
  zoo1:
    image: zookeeper:3.4.13
    container_name: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
    networks:
      - eventing
  kafka:
    depends_on:
      - zoo1
    image: wurstmeister/kafka:2.11-2.0.1
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.133
#      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_CREATE_TOPICS: "object:14:1"
      KAFKA_LOG_DIRS: /kafka/kafka-logs
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 90000
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
#      KAFKA_ADVERTISED_PROTOCOL_NAME: OUTSIDE
      KAFKA_ADVERTISED_PORT: 9092
#      KAFKA_LOG_RETENTION_HOURS: 1
#      KAFKA_PROTOCOL_NAME: INSIDE
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://_{HOSTNAME_COMMAND}:9092
#      KAFKA_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_HOST_NAME: 0.0.0.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka:/kafka
    networks:
      eventing:

volumes:
  kafka:
    driver: local

networks:
  eventing:
    external: true
